# Generated by Django 2.2.3 on 2019-07-27 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190713_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.TextField(null=True, verbose_name='본문'),
        ),
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='아이디'),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='web.Board')),
            ],
        ),
    ]
